version: '3'
services:
  grobid:
    image: lfoppiano/grobid:0.7.0
  api:
    build: .
    environment:
    - GROBID_URL=grobid
    depends_on:
    - grobid
  proxy:
    build: ./proxy
    ports:
    - 8080:8080
    depends_on:
    - api
